services:
  db:
    build: ./mysql

    container_name: mysql-app-rm

    image: mysql-app-rm

    environment:
      MYSQL_ROOT_PASSWORD: U%bLQ+Ny%*p9C)kZ;AmUG@R
      MYSQL_USER: rm_user
      MYSQL_PASSWORD: vrB=(rNg}/PESe(Z!RmF%3[v9
      MYSQL_DATABASE: RoomieMatch

    ports:
      - 4406:3306

    volumes:
      - persistence_db_app_rm:/var/lib/mysql

    networks:
      - app_network

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 60s
      retries: 10




volumes:
  persistence_db_app_rm:




networks:
  app_network:
    external: true
